### ISSUE TITLE
404 page not found when editing delivery

### ISSUE THREAD

**Issue by AaronNeonDigital** [lunarphp/livewire-starter-kit#62]
Once you check out and fill out the checkout form, if you edit the address, and then o back to editing the delivery option you are prompted with a 404 error.

Easy to replicate! Found by Sarbu Marius, who has posted a video of the issue in question. https://sediu.darurialese.com/drive/d/s/t32mOyZsM4imMGWxKWRVYaFu0j9wr55U/U5b7RBO2cl8DPjj04NIGg3BVwUYvZ3t--BrqAbLx_Vwo

**Comment by sarbumarius** [comment]
![Uploading Screenshot 2023-04-06 at 10.31.05.png…]()

**Comment by sarbumarius** [comment]
<img width="1677" alt="Screenshot 2023-04-06 at 10 27 13" src="https://user-images.githubusercontent.com/73889217/230307057-f6ede1cb-cfb7-4118-bae3-626f36bea5e8.png">
<img width="1093" alt="Screenshot 2023-04-06 at 10 27 06" src="https://user-images.githubusercontent.com/73889217/230307061-ea63c3fd-ac23-4073-8694-94036e0d9bd1.png">
<img width="1092" alt="Screenshot 2023-04-06 at 10 26 58" src="https://user-images.githubusercontent.com/73889217/230307064-370334cd-f42d-4179-9308-609a1079b40f.png">

**Comment by sarbumarius** [comment]
<img width="1173" alt="Screenshot 2023-04-06 at 10 31 05" src="https://user-images.githubusercontent.com/73889217/230307307-4c743b10-b2df-4fd1-a003-c23e53a30d5a.png">
<img width="1124" alt="Screenshot 2023-04-06 at 10 33 20" src="https://user-images.githubusercontent.com/73889217/230307314-02d60ff9-e8a0-4a32-963c-94dd0578929b.png">

**Comment by sarbumarius** [comment]
I tested on 2 servers, one with Synology and one with cPanel, both give the same error. However, on Lunar 0.1.6 with Laravel 8.83 and PHP 8.0, there is no error.
<img width="1161" alt="Screenshot 2023-04-06 at 10 42 31" src="https://user-images.githubusercontent.com/73889217/230309077-83e9097d-e24a-49b4-b193-8c1c11bc080e.png">

https://ai.darurialese.com:855/ (modified) working php 8.0.23- laravel 8.86 - synology. Lunar 1.0.6
https://ai.darurialese.com:856/   (fresh install)  not working  8.0.23- laravel 9.52.5- cpanel Lunar 0.2.3

http://ai.darurialese.ro/. (modified)  not working php 8.1 - laravel 9.52.5- cpanel Lunar 0.2.3
http://jack.darurialese.ro/ (fresh install)  not working  8.1 - laravel 9.52.5 - cpanel  Lunar 0.2.3

**Comment by alecritson** [comment]
I've pushed an update to the `main` branch which hopefully fixes this, you can see the changes required here: https://github.com/lunarphp/livewire-starter-kit/commit/e5c33d75bd8f2f9ea7a7d3a7f7bb53002401e3fc

If it's still a problem, reopen and we can take a look.
