### ISSUE TITLE
demo error

### ISSUE THREAD

**Issue by gravoline** [lunarphp/livewire-starter-kit#65]
Hello,
(sorry for my english, i am french)

I've just install the stater kit by following the instructions and when i launch it, this error appears :

Class "NumberFormatter" not found
resources/views/components/product-price.blade.php: 2

Some one can help me ? thanks.

Jean Philippe

**Comment by glennjacobs** [comment]
You haven't got the required PHP extensions installed. For this error you specifically need the Intl extension. 

See Lunar's requirements https://docs.lunarphp.io/core/installation.html
