### ISSUE TITLE
Class Number Formatter not found

### ISSUE THREAD

**Issue by HermanCeaser** [lunarphp/livewire-starter-kit#70]
- I installed everything fine by following the docs but when I opened the project in the browser after running  `php artisan serve`, I got this [Error Link](https://flareapp.io/share/oPR0DBJ5#context-custom-context-context)
- It Seems that Formatter is a helper class but I can't find it either.
- Did I Miss something ?

## Screenshot attached below
![code-snippet](https://i.ibb.co/X3q37DY/Screenshot-from-2023-08-06-14-24-23.png)

**Comment by HermanCeaser** [comment]
Why hasn't anyone looked at this 😔

**Comment by glennjacobs** [comment]
You have not installed the requirements as set out in the docs. 

And be more respectful in future please.

**Comment by HermanCeaser** [comment]
Am sorry if i came off as unrespectful, it wasn't my intention. I just wanted this to work and i was wondering if i missed out anything.  Thank you. Let me give it a try again.

**Comment by HermanCeaser** [comment]
I found the Issue. I didn't have the [Native PHP Formatter](https://www.php.net/manual/en/intl.installation.php) on my machine. I didn't know it was a requirement. It could be added in the requirement list on the docs. Thank you

**Comment by glennjacobs** [comment]
It's in the docs as "intl PHP extension". 

I think we'll try add some sort of check for this in a future release.
