### ISSUE TITLE
Product page displaying description with the html tags

### ISSUE THREAD

**Issue by vaimeo** [lunarphp/livewire-starter-kit#81]
<img width="1109" alt="image" src="https://github.com/lunarphp/livewire-starter-kit/assets/3579069/891465d3-0a27-4afe-a795-21bf8d6e21b6">

**Comment by alecritson** [comment]
You can just change the view to something like `{!! $product->attr('description') !!}` in order to render the HTML tags properly. This is Blade just escaping tags as expected.

https://laravel.com/docs/10.x/blade#displaying-unescaped-data
