### ISSUE TITLE
MediaLibrary adding white paddings

### ISSUE THREAD

**Issue by kylym1631** [lunarphp/livewire-starter-kit#83]
When adding images to products, if it is not square, white paddings are being added automatically. 
I don't know if it is a starter kit configuration or media-library.
Where exactly can I configure this. I want it to be sth like "object-fit:cover"
![Screenshot 2024-01-21 at 17 15 26](https://github.com/lunarphp/livewire-starter-kit/assets/67018582/9a3af9ef-7da7-4663-85cb-1821437a8a5b)

**Comment by alecritson** [comment]
This will be from the Media library package, you should be able to define your own conversions in the config https://docs.lunarphp.io/core/reference/images.html#conversions
