### ISSUE TITLE
Cart isn't properly associating with Order

### ISSUE THREAD

**Issue by devmanda** [lunarphp/livewire-starter-kit#88]
It seems like the cart isn't properly associating with an order when one is placed. I am being redirected to home on order success instead of the success page, with the error of "Cannot assign null to property App\Livewire\CheckoutSuccessPage::$order of type Lunar\Models\Order". 

Full Error Tracking: 
https://flareapp.io/share/87nXeNym#stack

**Comment by alecritson** [comment]
Thanks for reporting @devmanda this has come up a few times, the issue is the time between Lunar processing Stripe's webhook and having a completed order available.

I've put together a quick PR (which should be linked to this issue now) to demonstrate how you can solve this :)

**Comment by devmanda** [comment]
Thank you! Will try that
